### ISSUE TITLE
expects import "code.gitea.io/tea"

### ISSUE THREAD

**Issue by LittleColin** [go-gitea/tea#10]
running:
`go get github.com/go-gitea/tea`

Gives:
`package github.com/go-gitea/tea: code in directory C:\Users\<me>\go\src\github.com\go-gitea\tea expects import "code.gitea.io/tea"`

The readme doesn't mention how that should get resolved.

I tried:
`go get code.gitea.io/tea`

This silently returned, but subsequently running the following failed with the same error above:
`go install github.com/go-gitea/tea`

Can you add a built release of this tool?

**Comment by techknowlogick** [comment]
Could you try `go install code.gitea.io/tea`? As we will be moving away from Github we have go vanity URLs that protect from any move between repo locations.

**Comment by LittleColin** [comment]
Thanks for the fast reply. Just tried that and it silently returned but subsequently typing "tea" is not recognised.

Adding $home/go/bin to path resolved the issue. Is this worth documenting for go newcomers/agnostics?

Thanks again
