### ISSUE TITLE
go get fails

### ISSUE THREAD

**Issue by noerw** [go-gitea/tea#5]
I cant download the package as suggested (`go get github.com/go-gitea/tea`), it fails with the following error message:

```
can't load package: package github.com/go-gitea/tea: code in directory /home/norwin/src/github.com/go-gitea/tea expects import "code.gitea.io/tea"
```

Doing `go get code.gitea.io/tea` works, but this package seems to not represent the current version from github.

**Comment by noerw** [comment]
Ok, I got my dev environment set up the following way. I suppose thats not the right way?
```sh
mkdir -p $GOPATH/src/github.com/go-gitea
cd $GOPATH/src/github.com/go-gitea
git clone https://github.com/go-gitea/tea
cd tea
go get -v -d ./
```
Then in each of the `tea`, `go-sdk`, `git` repositories:
- replace all occurences of `code.gitea.io/sdk` with `github.com/go-gitea/go-sdk`
- replace all occurences of `code.gitea.io` with `github.com/go-gitea`

then run `go get -v -d ./` again.

**Comment by techknowlogick** [comment]
@lunny I’m on mobile so I can’t check now but I think this can be solved
by adding a new redirect in the go-gitea/redirects repo

**Comment by techknowlogick** [comment]
https://github.com/go-gitea/redirects/pull/44 hopefully fixes things

**Comment by techknowlogick** [comment]
Closing due to related merge. Please re-open if things still don't work.

**Comment by noerw** [comment]
Now I get the following error:
```
$ go get code.gitea.io/tea
package code.gitea.io/sdk/gitea: unrecognized import path "code.gitea.io/sdk/gitea" (parse https://code.gitea.io/sdk/gitea?go-get=1: no go-import meta tags ())                                                   
```

It seems that the code.gitea.io does not support sub-modules?
(It seems I can't reopen the issue)
